# Generated by Django 3.1.4 on 2021-03-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name_product_category',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name_product_type',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
